//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v201
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class FirmwareStatusNotificationRequest_CustomDataType
    {

        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;



        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// This contains the progress status of the firmware installation.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum FirmwareStatusNotificationRequest_FirmwareStatusEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Downloaded")]
        Downloaded = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"DownloadFailed")]
        DownloadFailed = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Downloading")]
        Downloading = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"DownloadScheduled")]
        DownloadScheduled = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"DownloadPaused")]
        DownloadPaused = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Idle")]
        Idle = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"InstallationFailed")]
        InstallationFailed = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Installing")]
        Installing = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"Installed")]
        Installed = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"InstallRebooting")]
        InstallRebooting = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"InstallScheduled")]
        InstallScheduled = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"InstallVerificationFailed")]
        InstallVerificationFailed = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"InvalidSignature")]
        InvalidSignature = 12,


        [System.Runtime.Serialization.EnumMember(Value = @"SignatureVerified")]
        SignatureVerified = 13,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class FirmwareStatusNotificationRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public FirmwareStatusNotificationRequest_CustomDataType CustomData { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public FirmwareStatusNotificationRequest_FirmwareStatusEnumType Status { get; set; } = default!;

        /// <summary>
        /// The request id that was provided in the
        /// <br/>UpdateFirmwareRequest that started this firmware update.
        /// <br/>This field is mandatory, unless the message was triggered by a TriggerMessageRequest AND there is no firmware update ongoing.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("requestId")]
        public int RequestId { get; set; } = default!;


    }
}