//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v201
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetInstalledCertificateIdsRequest_CustomDataType
    {

        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;



        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum GetInstalledCertificateIdsRequest_GetCertificateIdUseEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"V2GRootCertificate")]
        V2GRootCertificate = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"MORootCertificate")]
        MORootCertificate = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"CSMSRootCertificate")]
        CSMSRootCertificate = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"V2GCertificateChain")]
        V2GCertificateChain = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"ManufacturerRootCertificate")]
        ManufacturerRootCertificate = 4,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetInstalledCertificateIdsRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public GetInstalledCertificateIdsRequest_CustomDataType CustomData { get; set; } = default!;

        /// <summary>
        /// Indicates the type of certificates requested. When omitted, all certificate types are requested.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("certificateType")]

        // TODO(system.text.json): Add string enum item converter
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<GetInstalledCertificateIdsRequest_GetCertificateIdUseEnumType> CertificateType { get; set; } = default!;


    }
}