//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v201
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReservationStatusUpdateRequest_CustomDataType
    {

        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;



        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// The updated reservation status.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReservationStatusUpdateRequest_ReservationUpdateStatusEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Expired")]
        Expired = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Removed")]
        Removed = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReservationStatusUpdateRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public ReservationStatusUpdateRequest_CustomDataType CustomData { get; set; } = default!;

        /// <summary>
        /// The ID of the reservation.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("reservationId")]
        public int ReservationId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("reservationUpdateStatus")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public ReservationStatusUpdateRequest_ReservationUpdateStatusEnumType ReservationUpdateStatus { get; set; } = default!;


    }
}