//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v201
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TriggerMessageRequest_CustomDataType
    {

        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;



        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Type of message to be triggered.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TriggerMessageRequest_MessageTriggerEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BootNotification")]
        BootNotification = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"LogStatusNotification")]
        LogStatusNotification = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"FirmwareStatusNotification")]
        FirmwareStatusNotification = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Heartbeat")]
        Heartbeat = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"MeterValues")]
        MeterValues = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"SignChargingStationCertificate")]
        SignChargingStationCertificate = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"SignV2GCertificate")]
        SignV2GCertificate = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"StatusNotification")]
        StatusNotification = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"TransactionEvent")]
        TransactionEvent = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"SignCombinedCertificate")]
        SignCombinedCertificate = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"PublishFirmwareStatusNotification")]
        PublishFirmwareStatusNotification = 10,


    }

    /// <summary>
    /// EVSE
    /// <br/>urn:x-oca:ocpp:uid:2:233123
    /// <br/>Electric Vehicle Supply Equipment
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TriggerMessageRequest_EVSEType
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public TriggerMessageRequest_CustomDataType CustomData { get; set; } = default!;

        /// <summary>
        /// Identified_ Object. MRID. Numeric_ Identifier
        /// <br/>urn:x-enexis:ecdm:uid:1:569198
        /// <br/>EVSE Identifier. This contains a number (&amp;gt; 0) designating an EVSE of the Charging Station.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; } = default!;

        /// <summary>
        /// An id to designate a specific connector (on an EVSE) by connector index number.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("connectorId")]
        public int ConnectorId { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TriggerMessageRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public TriggerMessageRequest_CustomDataType CustomData { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("evse")]
        public TriggerMessageRequest_EVSEType Evse { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("requestedMessage")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public TriggerMessageRequest_MessageTriggerEnumType RequestedMessage { get; set; } = default!;


    }
}