//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v201
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UpdateFirmwareRequest_CustomDataType
    {

        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;



        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Firmware
    /// <br/>urn:x-enexis:ecdm:uid:2:233291
    /// <br/>Represents a copy of the firmware that can be loaded/updated on the Charging Station.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UpdateFirmwareRequest_FirmwareType
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public UpdateFirmwareRequest_CustomDataType CustomData { get; set; } = default!;

        /// <summary>
        /// Firmware. Location. URI
        /// <br/>urn:x-enexis:ecdm:uid:1:569460
        /// <br/>URI defining the origin of the firmware.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("location")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(512)]
        public string Location { get; set; } = default!;

        /// <summary>
        /// Firmware. Retrieve. Date_ Time
        /// <br/>urn:x-enexis:ecdm:uid:1:569461
        /// <br/>Date and time at which the firmware shall be retrieved.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("retrieveDateTime")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset RetrieveDateTime { get; set; } = default!;

        /// <summary>
        /// Firmware. Install. Date_ Time
        /// <br/>urn:x-enexis:ecdm:uid:1:569462
        /// <br/>Date and time at which the firmware shall be installed.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("installDateTime")]
        public System.DateTimeOffset InstallDateTime { get; set; } = default!;

        /// <summary>
        /// Certificate with which the firmware was signed.
        /// <br/>PEM encoded X.509 certificate.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("signingCertificate")]
        [System.ComponentModel.DataAnnotations.StringLength(5500)]
        public string SigningCertificate { get; set; } = default!;

        /// <summary>
        /// Firmware. Signature. Signature
        /// <br/>urn:x-enexis:ecdm:uid:1:569464
        /// <br/>Base64 encoded firmware signature.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("signature")]
        [System.ComponentModel.DataAnnotations.StringLength(800)]
        public string Signature { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UpdateFirmwareRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("customData")]
        public UpdateFirmwareRequest_CustomDataType CustomData { get; set; } = default!;

        /// <summary>
        /// This specifies how many times Charging Station must try to download the firmware before giving up. If this field is not present, it is left to Charging Station to decide how many times it wants to retry.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("retries")]
        public int Retries { get; set; } = default!;

        /// <summary>
        /// The interval in seconds after which a retry may be attempted. If this field is not present, it is left to Charging Station to decide how long to wait between attempts.
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("retryInterval")]
        public int RetryInterval { get; set; } = default!;

        /// <summary>
        /// The Id of this request
        /// <br/>
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("requestId")]
        public int RequestId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("firmware")]
        [System.ComponentModel.DataAnnotations.Required]
        public UpdateFirmwareRequest_FirmwareType Firmware { get; set; } = new UpdateFirmwareRequest_FirmwareType();


    }
}