//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class FirmwareStatusNotificationRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public FirmwareStatusNotificationRequestStatus Status { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum FirmwareStatusNotificationRequestStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Downloaded")]
        Downloaded = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"DownloadFailed")]
        DownloadFailed = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Downloading")]
        Downloading = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Idle")]
        Idle = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"InstallationFailed")]
        InstallationFailed = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Installing")]
        Installing = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Installed")]
        Installed = 6,


    }
}