//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetConfigurationResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("configurationKey")]
        public System.Collections.Generic.ICollection<GetConfigurationResponse_configurationKey> ConfigurationKey { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("unknownKey")]
        public System.Collections.Generic.ICollection<string> UnknownKey { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetConfigurationResponse_configurationKey
    {

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Key { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("readonly")]
        public bool Readonly { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.StringLength(500)]
        public string Value { get; set; } = default!;


    }
}