//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetCompositeScheduleResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public GetCompositeScheduleResponseStatus Status { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("connectorId")]
        public int ConnectorId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("scheduleStart")]
        public System.DateTimeOffset ScheduleStart { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingSchedule")]
        public GetCompositeScheduleResponse_ChargingSchedule ChargingSchedule { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum GetCompositeScheduleResponseStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Accepted")]
        Accepted = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Rejected")]
        Rejected = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetCompositeScheduleResponse_ChargingSchedule
    {

        [System.Text.Json.Serialization.JsonPropertyName("duration")]
        public int Duration { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("startSchedule")]
        public System.DateTimeOffset StartSchedule { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingRateUnit")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public GetCompositeScheduleResponse_ChargingScheduleChargingRateUnit ChargingRateUnit { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingSchedulePeriod")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<GetCompositeScheduleResponse_chargingSchedulePeriod> ChargingSchedulePeriod { get; set; } = new System.Collections.ObjectModel.Collection<GetCompositeScheduleResponse_chargingSchedulePeriod>();


        [System.Text.Json.Serialization.JsonPropertyName("minChargingRate")]
        public double MinChargingRate { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum GetCompositeScheduleResponse_ChargingScheduleChargingRateUnit
    {

        [System.Runtime.Serialization.EnumMember(Value = @"A")]
        A = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"W")]
        W = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetCompositeScheduleResponse_chargingSchedulePeriod
    {

        [System.Text.Json.Serialization.JsonPropertyName("startPeriod")]
        public int StartPeriod { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public double Limit { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("numberPhases")]
        public int NumberPhases { get; set; } = default!;


    }
}