//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RemoteStartTransactionRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("connectorId")]
        public int ConnectorId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("idTag")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string IdTag { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingProfile")]
        public RemoteStartTransactionRequest_ChargingProfile ChargingProfile { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RemoteStartTransactionRequest_ChargingProfile
    {

        [System.Text.Json.Serialization.JsonPropertyName("chargingProfileId")]
        public int ChargingProfileId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("transactionId")]
        public int TransactionId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("stackLevel")]
        public int StackLevel { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingProfilePurpose")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public RemoteStartTransactionRequest_ChargingProfileChargingProfilePurpose ChargingProfilePurpose { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingProfileKind")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public RemoteStartTransactionRequest_ChargingProfileChargingProfileKind ChargingProfileKind { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("recurrencyKind")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public RemoteStartTransactionRequest_ChargingProfileRecurrencyKind RecurrencyKind { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("validFrom")]
        public System.DateTimeOffset ValidFrom { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("validTo")]
        public System.DateTimeOffset ValidTo { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingSchedule")]
        [System.ComponentModel.DataAnnotations.Required]
        public RemoteStartTransactionRequest_ChargingSchedule ChargingSchedule { get; set; } = new RemoteStartTransactionRequest_ChargingSchedule();


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RemoteStartTransactionRequest_ChargingProfileChargingProfilePurpose
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ChargePointMaxProfile")]
        ChargePointMaxProfile = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"TxDefaultProfile")]
        TxDefaultProfile = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"TxProfile")]
        TxProfile = 2,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RemoteStartTransactionRequest_ChargingProfileChargingProfileKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Absolute")]
        Absolute = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Recurring")]
        Recurring = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Relative")]
        Relative = 2,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RemoteStartTransactionRequest_ChargingProfileRecurrencyKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Daily")]
        Daily = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Weekly")]
        Weekly = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RemoteStartTransactionRequest_ChargingSchedule
    {

        [System.Text.Json.Serialization.JsonPropertyName("duration")]
        public int Duration { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("startSchedule")]
        public System.DateTimeOffset StartSchedule { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingRateUnit")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public RemoteStartTransactionRequest_ChargingScheduleChargingRateUnit ChargingRateUnit { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("chargingSchedulePeriod")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<RemoteStartTransactionRequest_chargingSchedulePeriod> ChargingSchedulePeriod { get; set; } = new System.Collections.ObjectModel.Collection<RemoteStartTransactionRequest_chargingSchedulePeriod>();


        [System.Text.Json.Serialization.JsonPropertyName("minChargingRate")]
        public double MinChargingRate { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RemoteStartTransactionRequest_ChargingScheduleChargingRateUnit
    {

        [System.Runtime.Serialization.EnumMember(Value = @"A")]
        A = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"W")]
        W = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RemoteStartTransactionRequest_chargingSchedulePeriod
    {

        [System.Text.Json.Serialization.JsonPropertyName("startPeriod")]
        public int StartPeriod { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public double Limit { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("numberPhases")]
        public int NumberPhases { get; set; } = default!;


    }
}