//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SendLocalListRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("listVersion")]
        public int ListVersion { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("localAuthorizationList")]
        public System.Collections.Generic.ICollection<SendLocalListRequest_localAuthorizationList> LocalAuthorizationList { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("updateType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public SendLocalListRequestUpdateType UpdateType { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SendLocalListRequest_localAuthorizationList
    {

        [System.Text.Json.Serialization.JsonPropertyName("idTag")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string IdTag { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("idTagInfo")]
        public SendLocalListRequest_IdTagInfo IdTagInfo { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SendLocalListRequestUpdateType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Differential")]
        Differential = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Full")]
        Full = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SendLocalListRequest_IdTagInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("expiryDate")]
        public System.DateTimeOffset ExpiryDate { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("parentIdTag")]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string ParentIdTag { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public SendLocalListRequest_IdTagInfoStatus Status { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SendLocalListRequest_IdTagInfoStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Accepted")]
        Accepted = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Blocked")]
        Blocked = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Expired")]
        Expired = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Invalid")]
        Invalid = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"ConcurrentTx")]
        ConcurrentTx = 4,


    }
}