//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StatusNotificationRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("connectorId")]
        public int ConnectorId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("errorCode")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StatusNotificationRequestErrorCode ErrorCode { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("info")]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Info { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StatusNotificationRequestStatus Status { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        public System.DateTimeOffset Timestamp { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("vendorId")]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string VendorId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("vendorErrorCode")]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string VendorErrorCode { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StatusNotificationRequestErrorCode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ConnectorLockFailure")]
        ConnectorLockFailure = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"EVCommunicationError")]
        EVCommunicationError = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"GroundFailure")]
        GroundFailure = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"HighTemperature")]
        HighTemperature = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"InternalError")]
        InternalError = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"LocalListConflict")]
        LocalListConflict = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"NoError")]
        NoError = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"OtherError")]
        OtherError = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"OverCurrentFailure")]
        OverCurrentFailure = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"PowerMeterFailure")]
        PowerMeterFailure = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"PowerSwitchFailure")]
        PowerSwitchFailure = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"ReaderFailure")]
        ReaderFailure = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"ResetFailure")]
        ResetFailure = 12,


        [System.Runtime.Serialization.EnumMember(Value = @"UnderVoltage")]
        UnderVoltage = 13,


        [System.Runtime.Serialization.EnumMember(Value = @"OverVoltage")]
        OverVoltage = 14,


        [System.Runtime.Serialization.EnumMember(Value = @"WeakSignal")]
        WeakSignal = 15,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StatusNotificationRequestStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Available")]
        Available = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Preparing")]
        Preparing = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Charging")]
        Charging = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"SuspendedEVSE")]
        SuspendedEVSE = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"SuspendedEV")]
        SuspendedEV = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Finishing")]
        Finishing = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Reserved")]
        Reserved = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Unavailable")]
        Unavailable = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"Faulted")]
        Faulted = 8,


    }
}