//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StopTransactionRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("idTag")]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string IdTag { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("meterStop")]
        public int MeterStop { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Timestamp { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("transactionId")]
        public int TransactionId { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequestReason Reason { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("transactionData")]
        public System.Collections.Generic.ICollection<StopTransactionRequest_transactionData> TransactionData { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequestReason
    {

        [System.Runtime.Serialization.EnumMember(Value = @"EmergencyStop")]
        EmergencyStop = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"EVDisconnected")]
        EVDisconnected = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"HardReset")]
        HardReset = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Local")]
        Local = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"Other")]
        Other = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"PowerLoss")]
        PowerLoss = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Reboot")]
        Reboot = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Remote")]
        Remote = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"SoftReset")]
        SoftReset = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"UnlockCommand")]
        UnlockCommand = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"DeAuthorized")]
        DeAuthorized = 10,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StopTransactionRequest_transactionData
    {

        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Timestamp { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("sampledValue")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<StopTransactionRequest_sampledValue> SampledValue { get; set; } = new System.Collections.ObjectModel.Collection<StopTransactionRequest_sampledValue>();


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StopTransactionRequest_sampledValue
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Value { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("context")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValueContext Context { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("format")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValueFormat Format { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("measurand")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValueMeasurand Measurand { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("phase")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValuePhase Phase { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("location")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValueLocation Location { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("unit")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public StopTransactionRequest_sampledValueUnit Unit { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValueContext
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Interruption.Begin")]
        Interruption_Begin = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Interruption.End")]
        Interruption_End = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Sample.Clock")]
        Sample_Clock = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Sample.Periodic")]
        Sample_Periodic = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"Transaction.Begin")]
        Transaction_Begin = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Transaction.End")]
        Transaction_End = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Trigger")]
        Trigger = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Other")]
        Other = 7,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValueFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Raw")]
        Raw = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"SignedData")]
        SignedData = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValueMeasurand
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Active.Export.Register")]
        Energy_Active_Export_Register = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Active.Import.Register")]
        Energy_Active_Import_Register = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Reactive.Export.Register")]
        Energy_Reactive_Export_Register = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Reactive.Import.Register")]
        Energy_Reactive_Import_Register = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Active.Export.Interval")]
        Energy_Active_Export_Interval = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Active.Import.Interval")]
        Energy_Active_Import_Interval = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Reactive.Export.Interval")]
        Energy_Reactive_Export_Interval = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Energy.Reactive.Import.Interval")]
        Energy_Reactive_Import_Interval = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Active.Export")]
        Power_Active_Export = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Active.Import")]
        Power_Active_Import = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Offered")]
        Power_Offered = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Reactive.Export")]
        Power_Reactive_Export = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Reactive.Import")]
        Power_Reactive_Import = 12,


        [System.Runtime.Serialization.EnumMember(Value = @"Power.Factor")]
        Power_Factor = 13,


        [System.Runtime.Serialization.EnumMember(Value = @"Current.Import")]
        Current_Import = 14,


        [System.Runtime.Serialization.EnumMember(Value = @"Current.Export")]
        Current_Export = 15,


        [System.Runtime.Serialization.EnumMember(Value = @"Current.Offered")]
        Current_Offered = 16,


        [System.Runtime.Serialization.EnumMember(Value = @"Voltage")]
        Voltage = 17,


        [System.Runtime.Serialization.EnumMember(Value = @"Frequency")]
        Frequency = 18,


        [System.Runtime.Serialization.EnumMember(Value = @"Temperature")]
        Temperature = 19,


        [System.Runtime.Serialization.EnumMember(Value = @"SoC")]
        SoC = 20,


        [System.Runtime.Serialization.EnumMember(Value = @"RPM")]
        RPM = 21,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValuePhase
    {

        [System.Runtime.Serialization.EnumMember(Value = @"L1")]
        L1 = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"L2")]
        L2 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"L3")]
        L3 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"N")]
        N = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"L1-N")]
        L1N = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"L2-N")]
        L2N = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"L3-N")]
        L3N = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"L1-L2")]
        L1L2 = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"L2-L3")]
        L2L3 = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"L3-L1")]
        L3L1 = 9,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValueLocation
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Cable")]
        Cable = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"EV")]
        EV = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Inlet")]
        Inlet = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Outlet")]
        Outlet = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"Body")]
        Body = 4,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StopTransactionRequest_sampledValueUnit
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Wh")]
        Wh = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"kWh")]
        KWh = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"varh")]
        Varh = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"kvarh")]
        Kvarh = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"W")]
        W = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"kW")]
        KW = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"VA")]
        VA = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"kVA")]
        KVA = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"var")]
        Var = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"kvar")]
        Kvar = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"A")]
        A = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"V")]
        V = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"K")]
        K = 12,


        [System.Runtime.Serialization.EnumMember(Value = @"Celcius")]
        Celcius = 13,


        [System.Runtime.Serialization.EnumMember(Value = @"Fahrenheit")]
        Fahrenheit = 14,


        [System.Runtime.Serialization.EnumMember(Value = @"Percent")]
        Percent = 15,


    }
}