//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace NOCPP.Schemas.v16
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TriggerMessageRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("requestedMessage")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public TriggerMessageRequestRequestedMessage RequestedMessage { get; set; } = default!;


        [System.Text.Json.Serialization.JsonPropertyName("connectorId")]
        public int ConnectorId { get; set; } = default!;


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TriggerMessageRequestRequestedMessage
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BootNotification")]
        BootNotification = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"DiagnosticsStatusNotification")]
        DiagnosticsStatusNotification = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"FirmwareStatusNotification")]
        FirmwareStatusNotification = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"Heartbeat")]
        Heartbeat = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"MeterValues")]
        MeterValues = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"StatusNotification")]
        StatusNotification = 5,


    }
}